#!/bin/bash
# Event Radar - Weekly Reminder Script
# 每週提醒更新活動資料

echo "=============================================="
echo "🎯 Event Radar - 本週工作提醒"
echo "=============================================="
echo ""
echo "📅 今天: $(date '+%Y-%m-%d %A')"
echo ""
echo "本周任務："
echo ""
echo "1. 📚 HKPL 圖書館"
echo "   URL: https://www.hkpl.gov.hk/tc/extension-activities/all-events/this-week"
echo "   步驟: 用 Instant Data Scraper 抓取 → 導出 CSV → 運行 import_csv.py"
echo ""
echo "2. 🔬 香港科學館"
echo "   URL: https://hk.science.museum/tc/web/scm/event-calendar.html"
echo "   步驟: 篩選『兒童節目』→ 抓取活動"
echo ""
echo "3. 🏛️ 康文署"
echo "   URL: https://www.lcsd.gov.hk/clpss/tc/search/culture/GeneralSearchForm.do"
echo "   步驟: 搜尋『親子』→ 抓取結果"
echo ""
echo "4. 🏛️ 香港故宮"
echo "   URL: https://www.hkpm.org.hk/tc/event"
echo "   步驟: 瀏覽活動頁 → 抓取親子相關"
echo ""
echo "=============================================="
echo "💡 提示"
echo "=============================================="
echo ""
echo "快速導入命令:"
echo "  cd event-radar"
echo "  source venv/bin/activate"
echo "  python import_csv.py your_file.csv 'SourceName'"
echo ""
echo "查看完整指南:"
echo "  cat event-radar/README_MANUAL.md"
echo ""
echo "=============================================="
